dist: trusty
language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:

install:
  - composer install

script:
   - vendor/bin/phpspec run --no-interaction
   - vendor/bin/phpunit tests
